title: Portfolio of Surendra Singh
description: A brief summary of all the projects I have done, mostly on data science and machine learning. 
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
